spring.application.name=nexus-commerce-platform
server.port=9093
spring.datasource.url=jdbc:posgresql://localhost:5432/nexus-commerce-platform
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=nexus
spring.datasource.password=nexus
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true